"""Create Game Model

Revision ID: 2517b90ba5eb
Revises: 819428925848
Create Date: 2023-11-10 02:15:28.411822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2517b90ba5eb'
down_revision = '819428925848'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
