"""Add Review Model

Revision ID: 6aac18ae8eda
Revises: 2517b90ba5eb
Create Date: 2023-11-10 02:15:54.635900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aac18ae8eda'
down_revision = '2517b90ba5eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
