"""Create Game Model

Revision ID: 819428925848
Revises: 9551ec5f0421
Create Date: 2023-11-10 02:10:18.945443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819428925848'
down_revision = '9551ec5f0421'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
